/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as CheckoutCancelledRouteImport } from './routes/checkout.cancelled'
import { Route as CheckoutSlugRouteImport } from './routes/checkout.$slug'
import { Route as AuthenticatedMyTicketsRouteImport } from './routes/_authenticated/my-tickets'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedTicketsIdRouteImport } from './routes/_authenticated/tickets.$id'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin/payments'
import { Route as AuthenticatedAdminCheckinRouteImport } from './routes/_authenticated/admin/checkin'
import { Route as ApiPublicWebhooksStripeRouteImport } from './routes/api/public/webhooks/stripe'
import { Route as ApiPublicWebhooksMercadopagoRouteImport } from './routes/api/public/webhooks/mercadopago'
import { Route as AuthenticatedAdminEventsNewRouteImport } from './routes/_authenticated/admin/events.new'
import { Route as AuthenticatedAdminEventsIdRouteImport } from './routes/_authenticated/admin/events.$id'
import { Route as AuthenticatedAdminEventsIdAttendeesRouteImport } from './routes/_authenticated/admin/events.$id_.attendees'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutCancelledRoute = CheckoutCancelledRouteImport.update({
  id: '/checkout/cancelled',
  path: '/checkout/cancelled',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSlugRoute = CheckoutSlugRouteImport.update({
  id: '/checkout/$slug',
  path: '/checkout/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMyTicketsRoute = AuthenticatedMyTicketsRouteImport.update({
  id: '/my-tickets',
  path: '/my-tickets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedTicketsIdRoute = AuthenticatedTicketsIdRouteImport.update({
  id: '/tickets/$id',
  path: '/tickets/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCheckinRoute =
  AuthenticatedAdminCheckinRouteImport.update({
    id: '/checkin',
    path: '/checkin',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const ApiPublicWebhooksStripeRoute = ApiPublicWebhooksStripeRouteImport.update({
  id: '/api/public/webhooks/stripe',
  path: '/api/public/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksMercadopagoRoute =
  ApiPublicWebhooksMercadopagoRouteImport.update({
    id: '/api/public/webhooks/mercadopago',
    path: '/api/public/webhooks/mercadopago',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminEventsNewRoute =
  AuthenticatedAdminEventsNewRouteImport.update({
    id: '/events/new',
    path: '/events/new',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEventsIdRoute =
  AuthenticatedAdminEventsIdRouteImport.update({
    id: '/events/$id',
    path: '/events/$id',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEventsIdAttendeesRoute =
  AuthenticatedAdminEventsIdAttendeesRouteImport.update({
    id: '/events/$id_/attendees',
    path: '/events/$id/attendees',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/my-tickets': typeof AuthenticatedMyTicketsRoute
  '/checkout/$slug': typeof CheckoutSlugRoute
  '/checkout/cancelled': typeof CheckoutCancelledRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/events/$slug': typeof EventsSlugRoute
  '/admin/checkin': typeof AuthenticatedAdminCheckinRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/tickets/$id': typeof AuthenticatedTicketsIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/events/$id': typeof AuthenticatedAdminEventsIdRoute
  '/admin/events/new': typeof AuthenticatedAdminEventsNewRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
  '/admin/events/$id/attendees': typeof AuthenticatedAdminEventsIdAttendeesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/my-tickets': typeof AuthenticatedMyTicketsRoute
  '/checkout/$slug': typeof CheckoutSlugRoute
  '/checkout/cancelled': typeof CheckoutCancelledRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/events/$slug': typeof EventsSlugRoute
  '/admin/checkin': typeof AuthenticatedAdminCheckinRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/tickets/$id': typeof AuthenticatedTicketsIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/events/$id': typeof AuthenticatedAdminEventsIdRoute
  '/admin/events/new': typeof AuthenticatedAdminEventsNewRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
  '/admin/events/$id/attendees': typeof AuthenticatedAdminEventsIdAttendeesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/my-tickets': typeof AuthenticatedMyTicketsRoute
  '/checkout/$slug': typeof CheckoutSlugRoute
  '/checkout/cancelled': typeof CheckoutCancelledRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/events/$slug': typeof EventsSlugRoute
  '/_authenticated/admin/checkin': typeof AuthenticatedAdminCheckinRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/tickets/$id': typeof AuthenticatedTicketsIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/events/$id': typeof AuthenticatedAdminEventsIdRoute
  '/_authenticated/admin/events/new': typeof AuthenticatedAdminEventsNewRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
  '/_authenticated/admin/events/$id_/attendees': typeof AuthenticatedAdminEventsIdAttendeesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/reset-password'
    | '/admin'
    | '/my-tickets'
    | '/checkout/$slug'
    | '/checkout/cancelled'
    | '/checkout/success'
    | '/events/$slug'
    | '/admin/checkin'
    | '/admin/payments'
    | '/admin/settings'
    | '/admin/users'
    | '/tickets/$id'
    | '/admin/'
    | '/admin/events/$id'
    | '/admin/events/new'
    | '/api/public/webhooks/mercadopago'
    | '/api/public/webhooks/stripe'
    | '/admin/events/$id/attendees'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/reset-password'
    | '/my-tickets'
    | '/checkout/$slug'
    | '/checkout/cancelled'
    | '/checkout/success'
    | '/events/$slug'
    | '/admin/checkin'
    | '/admin/payments'
    | '/admin/settings'
    | '/admin/users'
    | '/tickets/$id'
    | '/admin'
    | '/admin/events/$id'
    | '/admin/events/new'
    | '/api/public/webhooks/mercadopago'
    | '/api/public/webhooks/stripe'
    | '/admin/events/$id/attendees'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/onboarding'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/my-tickets'
    | '/checkout/$slug'
    | '/checkout/cancelled'
    | '/checkout/success'
    | '/events/$slug'
    | '/_authenticated/admin/checkin'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/users'
    | '/_authenticated/tickets/$id'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/events/$id'
    | '/_authenticated/admin/events/new'
    | '/api/public/webhooks/mercadopago'
    | '/api/public/webhooks/stripe'
    | '/_authenticated/admin/events/$id_/attendees'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  CheckoutSlugRoute: typeof CheckoutSlugRoute
  CheckoutCancelledRoute: typeof CheckoutCancelledRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  EventsSlugRoute: typeof EventsSlugRoute
  ApiPublicWebhooksMercadopagoRoute: typeof ApiPublicWebhooksMercadopagoRoute
  ApiPublicWebhooksStripeRoute: typeof ApiPublicWebhooksStripeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/cancelled': {
      id: '/checkout/cancelled'
      path: '/checkout/cancelled'
      fullPath: '/checkout/cancelled'
      preLoaderRoute: typeof CheckoutCancelledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$slug': {
      id: '/checkout/$slug'
      path: '/checkout/$slug'
      fullPath: '/checkout/$slug'
      preLoaderRoute: typeof CheckoutSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/my-tickets': {
      id: '/_authenticated/my-tickets'
      path: '/my-tickets'
      fullPath: '/my-tickets'
      preLoaderRoute: typeof AuthenticatedMyTicketsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/tickets/$id': {
      id: '/_authenticated/tickets/$id'
      path: '/tickets/$id'
      fullPath: '/tickets/$id'
      preLoaderRoute: typeof AuthenticatedTicketsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/checkin': {
      id: '/_authenticated/admin/checkin'
      path: '/checkin'
      fullPath: '/admin/checkin'
      preLoaderRoute: typeof AuthenticatedAdminCheckinRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/public/webhooks/stripe': {
      id: '/api/public/webhooks/stripe'
      path: '/api/public/webhooks/stripe'
      fullPath: '/api/public/webhooks/stripe'
      preLoaderRoute: typeof ApiPublicWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/mercadopago': {
      id: '/api/public/webhooks/mercadopago'
      path: '/api/public/webhooks/mercadopago'
      fullPath: '/api/public/webhooks/mercadopago'
      preLoaderRoute: typeof ApiPublicWebhooksMercadopagoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/events/new': {
      id: '/_authenticated/admin/events/new'
      path: '/events/new'
      fullPath: '/admin/events/new'
      preLoaderRoute: typeof AuthenticatedAdminEventsNewRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/events/$id': {
      id: '/_authenticated/admin/events/$id'
      path: '/events/$id'
      fullPath: '/admin/events/$id'
      preLoaderRoute: typeof AuthenticatedAdminEventsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/events/$id_/attendees': {
      id: '/_authenticated/admin/events/$id_/attendees'
      path: '/events/$id/attendees'
      fullPath: '/admin/events/$id/attendees'
      preLoaderRoute: typeof AuthenticatedAdminEventsIdAttendeesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminCheckinRoute: typeof AuthenticatedAdminCheckinRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminEventsIdRoute: typeof AuthenticatedAdminEventsIdRoute
  AuthenticatedAdminEventsNewRoute: typeof AuthenticatedAdminEventsNewRoute
  AuthenticatedAdminEventsIdAttendeesRoute: typeof AuthenticatedAdminEventsIdAttendeesRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminCheckinRoute: AuthenticatedAdminCheckinRoute,
    AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
    AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminEventsIdRoute: AuthenticatedAdminEventsIdRoute,
    AuthenticatedAdminEventsNewRoute: AuthenticatedAdminEventsNewRoute,
    AuthenticatedAdminEventsIdAttendeesRoute:
      AuthenticatedAdminEventsIdAttendeesRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedMyTicketsRoute: typeof AuthenticatedMyTicketsRoute
  AuthenticatedTicketsIdRoute: typeof AuthenticatedTicketsIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedMyTicketsRoute: AuthenticatedMyTicketsRoute,
  AuthenticatedTicketsIdRoute: AuthenticatedTicketsIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  CheckoutSlugRoute: CheckoutSlugRoute,
  CheckoutCancelledRoute: CheckoutCancelledRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  EventsSlugRoute: EventsSlugRoute,
  ApiPublicWebhooksMercadopagoRoute: ApiPublicWebhooksMercadopagoRoute,
  ApiPublicWebhooksStripeRoute: ApiPublicWebhooksStripeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
